apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbridge-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudbridge-app
  template:
    metadata:
      labels:
        app: cloudbridge-app
    spec:
      containers:
        - name: cloudbridge-app
          image: zoya9545/cloudbridge-app:v1
          ports:
            - containerPort: 3000

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
